Yolo-v5 tflite model
tensorflow/tfhub.dev pull request #62
Opened 2021-07-07 08:03 UTC by neso613

Any pull request you open is subject to the TensorFlow Hub Terms of Service at www.tfhub.dev/terms.

2021-07-07 11:25 UTC, maringeo commented on assets/docs/neso613/yolo-v5-tflite/tflite_model/1.md
> +<!-- asset-path:  -->
You would need to provide the path to the tflite file. One way to do this is to upload it to some cloud storage (the tflite file needs to be publicly readable).

2021-07-13 20:00 UTC, WGierke requested changes
Hi @neso613,
Just like in PR #58, we also need you to host the TFLite file on a world-readable remote location for this PR. Feel free to reach out if you have any questions!

2021-07-26 08:28 UTC, merged

2021-07-26 08:30 UTC, WGierke commented
Thank you for your contribution @neso613 ! It'll take a few hours until the model is published. Once that happened, you can  remove the uploaded TFLite file again from your Cloud bucket if you want.

2021-07-26 08:34 UTC, neso613 commented
Thanks @WGierke.

2021-07-27 05:36 UTC, neso613 commented
@WGierke I have checked tfhub.dev. Model is not published yet. How much time it will take?

2021-07-28 07:54 UTC, neso613 commented
@maringeo Does the model publishing took time?

2021-07-28 08:00 UTC, maringeo commented
Hi @neso613, our publishing pipeline experienced some issues unrelated to this PR. The problem is close to being resolved, so I expect the model to be published soon (in the next day or two).

2021-07-28 11:26 UTC, WGierke commented
The model is live now: https://tfhub.dev/neso613/lite-model/yolo-v5-tflite/tflite_model/1 Sorry for the delay! The missing architecture tag should be added within a few days.

2021-07-28 12:26 UTC, neso613 commented
Thanks for updating me!